<template>
  <div
    class="gap-3 fixed top-5 left-1/2 z-150 -translate-x-1/2 flex flex-row rounded-full"
  >
    <AppBarItem
      to="/"
      label="Home"
      icon="solar:tea-cup-broken"
      active-icon="solar:tea-cup-bold"
    />
    <AppBarItem
      to="/project"
      label="Project"
      icon="solar:case-broken"
      active-icon="solar:case-bold"
    />
    <AppBarItem
      to="/blog"
      label="Blog"
      icon="solar:notes-broken"
      active-icon="solar:notes-bold"
    />
  </div>
</template>
